import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';

const washrooms = [
    {
        "ID": "1",
        "NAME": "Adanac Park",
        "ADDRESS": "1025 Boundary Road",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.275880967768586",
        "LONGITUDE": "-123.02407196031945",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "2",
        "NAME": "Andy Livingstone Park",
        "ADDRESS": "89 Expo Boulevard",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Downtown",
        "FIELD6": "10:00 am - 11:00 pm",
        "WINTERHOURS": "10:00 am - 11:00 pm",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.27782096652457",
        "LONGITUDE": "-123.10359902225629",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "3",
        "NAME": "Balaclava Park",
        "ADDRESS": "4594 Balaclava Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.24523399439745",
        "LONGITUDE": "-123.17546094936067",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "4",
        "NAME": "Barclay Heritage Square",
        "ADDRESS": "1433 Barclay Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Downtown",
        "FIELD6": "Hours of the centre",
        "WINTERHOURS": "Hours of the centre",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.28721486975494",
        "LONGITUDE": "-123.13256051091837",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "5",
        "NAME": "Beaconsfield Park",
        "ADDRESS": "3215 Slocan Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.25523299021206",
        "LONGITUDE": "-123.04993395932648",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "6",
        "NAME": "Bobolink Park",
        "ADDRESS": "2510 Hoylake Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.215606986748945",
        "LONGITUDE": "-123.0564149550414",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "7",
        "NAME": "Braemar Park",
        "ADDRESS": "895 W 27th Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Mt Pleasant",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.2474209947128",
        "LONGITUDE": "-123.12448302167117",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "8",
        "NAME": "Brewers Park",
        "ADDRESS": "4175 Victoria Drive",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Closed",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.24785499067069",
        "LONGITUDE": "-123.06542594907842",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "9",
        "NAME": "Burrard View Park",
        "ADDRESS": "650 North Penticton Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "No Caretaker",
        "LATITUDE": "49.290363962195194",
        "LONGITUDE": "-123.04964897084469",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "10",
        "NAME": "CRAB Park at Portside",
        "ADDRESS": "101 E Waterfront Road",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Downtown",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.28459200731105",
        "LONGITUDE": "-123.10183500413727",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "11",
        "NAME": "Carnarvon Park",
        "ADDRESS": "2995 W 19th Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.25674201688619",
        "LONGITUDE": "-123.17260901038105",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "12",
        "NAME": "Chaldecott Park",
        "ADDRESS": "4175 Wallace Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.24942696008366",
        "LONGITUDE": "-123.19112496205022",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "13",
        "NAME": "Clinton Park",
        "ADDRESS": "2690 Grant Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.27114503289929",
        "LONGITUDE": "-123.0497820278666",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "14",
        "NAME": "Collingwood Park",
        "ADDRESS": "5275 McKinnon Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.23652996374762",
        "LONGITUDE": "-123.0367159606789",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "15",
        "NAME": "Columbia Park",
        "ADDRESS": "5908 Alberta Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk Weekends only",
        "WINTERHOURS": "Dawn to Dusk Weekends only",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.231522997877",
        "LONGITUDE": "-123.11290897402343",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "16",
        "NAME": "David Lam Park",
        "ADDRESS": "1300 Pacific Boulevard",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Downtown",
        "FIELD6": "10:00 am - Dusk",
        "WINTERHOURS": "10:00 am - Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.272383007337496",
        "LONGITUDE": "-123.12541503516248",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "17",
        "NAME": "Elm Park",
        "ADDRESS": "5800 Elm Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.23343197922455",
        "LONGITUDE": "-123.16328394461392",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "18",
        "NAME": "English Bay Beach Park",
        "ADDRESS": "1700 Beach Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Downtown",
        "FIELD6": "7:00 am - Dusk",
        "WINTERHOURS": "10:00 am - Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.28615404002572",
        "LONGITUDE": "-123.14280496708423",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "19",
        "NAME": "Falaise Park",
        "ADDRESS": "3434 Falaise Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Women's is closed Mon - Fri during school days",
        "LATITUDE": "49.25512303467576",
        "LONGITUDE": "-123.02940598674489",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "20",
        "NAME": "Fraser River Park",
        "ADDRESS": "8705 Angus Drive",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Closed",
        "WHEELCHAIR": "No",
        "FIELD9": "April 1 to October 31",
        "LATITUDE": "49.20739499859824",
        "LONGITUDE": "-123.14985600453248",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "21",
        "NAME": "Fraserview Golf Course",
        "ADDRESS": "7800 Vivian Drive",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.211295351769444",
        "LONGITUDE": "-123.04229966758577",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "22",
        "NAME": "Garden Park",
        "ADDRESS": "1851 Garden Drive",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.268285998438586",
        "LONGITUDE": "-123.0583339940012",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "23",
        "NAME": "Gordon Park",
        "ADDRESS": "6675 Commercial Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.22387004506593",
        "LONGITUDE": "-123.06949997853391",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "24",
        "NAME": "Grandview Park",
        "ADDRESS": "1255 Commercial Drive",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.27376163132157",
        "LONGITUDE": "-123.06995444643604",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "25",
        "NAME": "Granville Park",
        "ADDRESS": "3001 Fir Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Mt Pleasant",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "No Caretaker",
        "LATITUDE": "49.25849301149994",
        "LONGITUDE": "-123.14196994988014",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "26",
        "NAME": "Grays Park",
        "ADDRESS": "4850 St. Catherines Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Mt Pleasant",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Closed",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.240787004601344",
        "LONGITUDE": "-123.08488703266472",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "27",
        "NAME": "Hadden Park",
        "ADDRESS": "1905 Ogden Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "No Caretaker",
        "LATITUDE": "49.27746099308929",
        "LONGITUDE": "-123.15030998211027",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "28",
        "NAME": "Harbour Green Park",
        "ADDRESS": "1199 W Cordova Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Downtown",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.28980401412553",
        "LONGITUDE": "-123.12146699859517",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "29",
        "NAME": "Hastings Community Park",
        "ADDRESS": "3000 E Pender Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Closed",
        "WHEELCHAIR": "No",
        "FIELD9": "No Caretaker",
        "LATITUDE": "49.28064797075682",
        "LONGITUDE": "-123.0378739491102",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "30",
        "NAME": "Jericho Beach Park",
        "ADDRESS": "3941 Point Grey Road",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.27158002127107",
        "LONGITUDE": "-123.19165895955678",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "31",
        "NAME": "Jericho Beach Park",
        "ADDRESS": "3941 Point Grey Road",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn - 11:00 pm",
        "WINTERHOURS": "Dawn - 11:00 pm",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.27442798898714",
        "LONGITUDE": "-123.20280599871978",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "32",
        "NAME": "John Hendry (Trout Lake) Park",
        "ADDRESS": "3300 Victoria Drive",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.25392603888665",
        "LONGITUDE": "-123.06138798885063",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "33",
        "NAME": "Jonathan Rogers Park",
        "ADDRESS": "110 W 7th Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Mt Pleasant",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.26449802992546",
        "LONGITUDE": "-123.10762001612511",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "34",
        "NAME": "Jones Park",
        "ADDRESS": "5350 Commercial Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.23620495899663",
        "LONGITUDE": "-123.06832802710548",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "35",
        "NAME": "Kitsilano Beach Park",
        "ADDRESS": "1499 Arbutus Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.27447199358691",
        "LONGITUDE": "-123.15370297467196",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "36",
        "NAME": "Kitsilano Beach Park",
        "ADDRESS": "1499 Arbutus Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.27301403401155",
        "LONGITUDE": "-123.15754296760241",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "37",
        "NAME": "Locarno Park",
        "ADDRESS": "4445 NW Marine Drive",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.27506599232316",
        "LONGITUDE": "-123.20655501307206",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "38",
        "NAME": "MacLean Park",
        "ADDRESS": "710 Keefer Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Chinatown",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "No Caretaker",
        "LATITUDE": "49.279007022880016",
        "LONGITUDE": "-123.08936604040026",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "39",
        "NAME": "Maple Grove Park",
        "ADDRESS": "6875 Yew Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.22338402151405",
        "LONGITUDE": "-123.15958297474762",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "40",
        "NAME": "McBride Park",
        "ADDRESS": "3350 W 4th Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "No Caretaker",
        "LATITUDE": "49.26810696654426",
        "LONGITUDE": "-123.18014096219831",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "41",
        "NAME": "Memorial South Park",
        "ADDRESS": "5955 Ross Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "No Caretaker",
        "LATITUDE": "49.230738034849644",
        "LONGITUDE": "-123.08438800261668",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "42",
        "NAME": "Memorial West Park",
        "ADDRESS": "4701 Dunbar Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Central, field house",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.24333498522083",
        "LONGITUDE": "-123.1884550030957",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "43",
        "NAME": "Moberly Park",
        "ADDRESS": "7646 Prince Albert Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.21525299594611",
        "LONGITUDE": "-123.08735497891107",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "44",
        "NAME": "Montgomery Park",
        "ADDRESS": "1040 W 43rd Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.231826046629344",
        "LONGITUDE": "-123.1292409864781",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "45",
        "NAME": "Nanaimo Park",
        "ADDRESS": "2390 E 46th Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "No Caretaker",
        "LATITUDE": "49.22824199904485",
        "LONGITUDE": "-123.05742904202303",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "46",
        "NAME": "New Brighton Park",
        "ADDRESS": "3201 New Brighton Road",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.289293",
        "LONGITUDE": "-123.036308",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "47",
        "NAME": "New Brighton Park",
        "ADDRESS": "3201 New Brighton Road",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.289333969962875",
        "LONGITUDE": "-123.03602500744294",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "48",
        "NAME": "Norquay Park",
        "ADDRESS": "5050 Wales Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "No Caretaker",
        "LATITUDE": "49.23797499034376",
        "LONGITUDE": "-123.05142495991136",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "49",
        "NAME": "Oak Park",
        "ADDRESS": "900 W 59th Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.21628599509403",
        "LONGITUDE": "-123.12764097865914",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "50",
        "NAME": "Oppenheimer Park",
        "ADDRESS": "400 Powell Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Downtown",
        "FIELD6": "Tue - Sat 9:00 am - 8:00 pm",
        "WINTERHOURS": "Tue - Sat 9:00 am - 5:00 pm",
        "WHEELCHAIR": "No",
        "FIELD9": "Family washroom available",
        "LATITUDE": "49.2829379681762",
        "LONGITUDE": "-123.09418103535418",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "51",
        "NAME": "Pandora Park",
        "ADDRESS": "2325 Franklin Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "9:00 am - 7:00 pm",
        "WINTERHOURS": "Closed",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.28227999867548",
        "LONGITUDE": "-123.05747804918629",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "52",
        "NAME": "Queen Elizabeth Park",
        "ADDRESS": "4600 Cambie Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Mt Pleasant",
        "FIELD6": "7:30 am - 9:00 pm",
        "WINTERHOURS": "7:30 am - 9:00 pm",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.242211017666655",
        "LONGITUDE": "-123.11284497531454",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "53",
        "NAME": "Queen Elizabeth Park",
        "ADDRESS": "4600 Cambie Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Mt Pleasant",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "No Caretaker",
        "LATITUDE": "49.23893801780079",
        "LONGITUDE": "-123.111577056628",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "54",
        "NAME": "Queen Elizabeth Park",
        "ADDRESS": "4600 Cambie Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Mt Pleasant",
        "FIELD6": "7:30 am - 9:00 pm",
        "WINTERHOURS": "7:30 am - 9:00 pm",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.24218396510625",
        "LONGITUDE": "-123.11291900335904",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "55",
        "NAME": "Quilchena Park",
        "ADDRESS": "4590 Magnolia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.2446430482962",
        "LONGITUDE": "-123.14872394485556",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "56",
        "NAME": "Riverfront Park",
        "ADDRESS": "2750 E Kent Street S",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.20576803764335",
        "LONGITUDE": "-123.05184697069491",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "57",
        "NAME": "Robson Park",
        "ADDRESS": "599 Kingsway",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Mt Pleasant",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.258627016444436",
        "LONGITUDE": "-123.0928489867954",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "58",
        "NAME": "Ross Park",
        "ADDRESS": "7402 Ross Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.216699980677504",
        "LONGITUDE": "-123.08279803502215",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "59",
        "NAME": "Rupert Park",
        "ADDRESS": "1600 Rupert Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.27013500419252",
        "LONGITUDE": "-123.03060497962684",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "60",
        "NAME": "Rupert Park",
        "ADDRESS": "1600 Rupert Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.2730500015562",
        "LONGITUDE": "-123.03068295926941",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "61",
        "NAME": "Slocan Park",
        "ADDRESS": "2750 E 29th Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.24443797840094",
        "LONGITUDE": "-123.04795201718906",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "62",
        "NAME": "Spanish Banks Beach Park",
        "ADDRESS": "4801 NW Marine Drive",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.276243975522064",
        "LONGITUDE": "-123.21492003747045",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "63",
        "NAME": "Spanish Banks Beach Park",
        "ADDRESS": "4801 NW Marine Drive",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.277471986024096",
        "LONGITUDE": "-123.22267905540143",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "64",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Wheelchair accessible",
        "LATITUDE": "49.29361699009479",
        "LONGITUDE": "-123.14871495670666",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "65",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "Yes, entered from parking lot level",
        "FIELD9": "Accessible washroom entered from parking lot level, to the left side of the building.",
        "LATITUDE": "49.29954903151692",
        "LONGITUDE": "-123.13405101608808",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "66",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Wheelchair accessible",
        "LATITUDE": "49.30292598470635",
        "LONGITUDE": "-123.13070797895129",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "67",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Wheelchair accessible",
        "LATITUDE": "49.297753014659136",
        "LONGITUDE": "-123.13143296609115",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "68",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "Yes, key available at Pitch and Putt ticket booth",
        "FIELD9": "Key to accessible washroom on west side of Fish House available at Pitch and Putt Golf Course ticket booth",
        "LATITUDE": "49.29229302155727",
        "LONGITUDE": "-123.14658004092536",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "69",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Wheelchair accessible",
        "LATITUDE": "49.293922038349855",
        "LONGITUDE": "-123.13859102939685",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "70",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Weekdays only 8:30 am - 5:00 pm",
        "WINTERHOURS": "Weekdays only 8:30 am - 5:00 pm",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Wheelchair accessible",
        "LATITUDE": "49.2908669672286",
        "LONGITUDE": "-123.14535496442156",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "71",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Wheelchair accessible",
        "LATITUDE": "49.295626992567065",
        "LONGITUDE": "-123.1507330006289",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "72",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Wheelchair accessible at parking lot level, Caretaker on site",
        "LATITUDE": "49.30315299202374",
        "LONGITUDE": "-123.15593104867578",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "73",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Wheelchair accessible",
        "LATITUDE": "49.299867995983135",
        "LONGITUDE": "-123.13070000486955",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "74",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Wheelchair accessible, Caretaker on site",
        "LATITUDE": "49.29962596459017",
        "LONGITUDE": "-123.12602300258104",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "75",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Not accessible, key to accessible washroom on west side of Fish House available at ticket booth",
        "LATITUDE": "49.29303503730124",
        "LONGITUDE": "-123.14659902476437",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "76",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Wheelchair accessible",
        "LATITUDE": "49.312412032074626",
        "LONGITUDE": "-123.14264998927618",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "77",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Wheelchair accessible, Caretaker on site",
        "LATITUDE": "49.31055002836116",
        "LONGITUDE": "-123.14838803989763",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "78",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Wheelchair accessible",
        "LATITUDE": "49.299440023527644",
        "LONGITUDE": "-123.12127801961992",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "79",
        "NAME": "Stanley Park",
        "ADDRESS": "2000 W Georgia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Stanley Park",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Wheelchair accessible",
        "LATITUDE": "49.30206900322541",
        "LONGITUDE": "-123.13292304217946",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "80",
        "NAME": "Strathcona Park",
        "ADDRESS": "857 Malkin Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Chinatown",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.27455700661123",
        "LONGITUDE": "-123.08618899175829",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "81",
        "NAME": "Sunrise Park",
        "ADDRESS": "1950 Windermere Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.26692299194362",
        "LONGITUDE": "-123.03601798246004",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "82",
        "NAME": "Sunset Beach Park",
        "ADDRESS": "1204 Beach Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Downtown",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "7:00 am - Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.278837014788635",
        "LONGITUDE": "-123.13795004349424",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "83",
        "NAME": "Tatlow Park",
        "ADDRESS": "2845 W 3rd Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.269476011814966",
        "LONGITUDE": "-123.16951194967828",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "84",
        "NAME": "Trafalgar Park",
        "ADDRESS": "2610 W 23rd Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.25155496641212",
        "LONGITUDE": "-123.16347197342456",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "85",
        "NAME": "Trillium Park",
        "ADDRESS": "600 National Avenue",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Chinatown",
        "FIELD6": "Dawn to 10:15 pm",
        "WINTERHOURS": "Dawn to 10:15 pm",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.2748",
        "LONGITUDE": "-123.09291104230556",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "86",
        "NAME": "VanDusen Botanical Garden",
        "ADDRESS": "5251 Oak Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Mt Pleasant",
        "FIELD6": "Hours of operation only",
        "WINTERHOURS": "Hours of operation only",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.23851044985559",
        "LONGITUDE": "-123.12863834016463",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "87",
        "NAME": "VanDusen Botanical Garden",
        "ADDRESS": "5251 Oak Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Mt Pleasant",
        "FIELD6": "Hours of operation only",
        "WINTERHOURS": "Hours of operation only",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.23865943271583",
        "LONGITUDE": "-123.12955764576705",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "88",
        "NAME": "Vanier Park",
        "ADDRESS": "1000 Chestnut Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Sometimes later in summer",
        "LATITUDE": "49.2751960118216",
        "LONGITUDE": "-123.13985594374256",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "89",
        "NAME": "Victoria Park",
        "ADDRESS": "1425 Victoria Drive",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "",
        "LATITUDE": "49.27174404280882",
        "LONGITUDE": "-123.06741301648843",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "90",
        "NAME": "West Point Grey Park",
        "ADDRESS": "2250 Trimble Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "Kitsilano",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.26654154338981",
        "LONGITUDE": "-123.20457956437797",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "91",
        "NAME": "Winona Park",
        "ADDRESS": "7575 Columbia Street",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "South Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.215717980350206",
        "LONGITUDE": "-123.11294894525255",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "92",
        "NAME": "Woodland Park",
        "ADDRESS": "705 Woodland Drive",
        "TYPE": "Public Toilet in Park",
        "LOCATION": "East Van",
        "FIELD6": "Dawn to Dusk",
        "WINTERHOURS": "Dawn to Dusk",
        "WHEELCHAIR": "No",
        "FIELD9": "Caretaker on site",
        "LATITUDE": "49.27836897224034",
        "LONGITUDE": "-123.07322000465284",
        "MAINTAINER": "Parks & Recreation"
    },
    {
        "ID": "100",
        "NAME": "Main at Hastings",
        "ADDRESS": "SW corner of intersection",
        "TYPE": "Comfort Station",
        "LOCATION": "Downtown",
        "FIELD6": "Men: 6am - Women: 8am to Midnight",
        "WINTERHOURS": "Men: 6am - Women: 8am to Midnight",
        "WHEELCHAIR": "No",
        "FIELD9": "N/A",
        "LATITUDE": "49.281107",
        "LONGITUDE": "-123.09985",
        "MAINTAINER": "City of Vancouver"
    },
    {
        "ID": "101",
        "NAME": "Victory Square",
        "ADDRESS": "N/A",
        "TYPE": "Comfort Station",
        "LOCATION": "Downtown",
        "FIELD6": "Men: 6am - Women: 8am to Midnight",
        "WINTERHOURS": "Men: 6am - Women: 8am to Midnight",
        "WHEELCHAIR": "No",
        "FIELD9": "N/A",
        "LATITUDE": "49.2825906",
        "LONGITUDE": "-123.110132",
        "MAINTAINER": "City of Vancouver"
    },
    {
        "ID": "102",
        "NAME": "Bute at Davie",
        "ADDRESS": "NE corner of intersection",
        "TYPE": "Automated Public Toilet",
        "LOCATION": "Downtown",
        "FIELD6": "24 hrs",
        "WINTERHOURS": "24 hrs",
        "WHEELCHAIR": "No",
        "FIELD9": "Please call 311 for maintenance requests",
        "LATITUDE": "49.2818541",
        "LONGITUDE": "-123.133141",
        "MAINTAINER": "City of Vancouver"
    },
    {
        "ID": "103",
        "NAME": "Hastings at Carral - Pigeon Park",
        "ADDRESS": "NW corner of intersection",
        "TYPE": "Automated Public Toilet",
        "LOCATION": "Downtown",
        "FIELD6": "24 hrs",
        "WINTERHOURS": "24 hrs",
        "WHEELCHAIR": "No",
        "FIELD9": "Please call 311 for maintenance requests",
        "LATITUDE": "49.2816384",
        "LONGITUDE": "-123.104602",
        "MAINTAINER": "City of Vancouver"
    },
    {
        "ID": "104",
        "NAME": "Main at Terminal",
        "ADDRESS": "NE corner of intersection",
        "TYPE": "Automated Public Toilet",
        "LOCATION": "Chinatown",
        "FIELD6": "8am to 3pm to N/A",
        "WINTERHOURS": "8am to 3pm to N/A",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Please call 311 for maintenance requests",
        "LATITUDE": "49.2731387",
        "LONGITUDE": "-123.099778",
        "MAINTAINER": "City of Vancouver"
    },
    {
        "ID": "105",
        "NAME": "Nelson Park",
        "ADDRESS": "West side of park",
        "TYPE": "Automated Public Toilet",
        "LOCATION": "Downtown",
        "FIELD6": "24 hrs",
        "WINTERHOURS": "24 hrs",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Please call 311 for maintenance requests",
        "LATITUDE": "49.283378",
        "LONGITUDE": "-123.130677",
        "MAINTAINER": "City of Vancouver"
    },
    {
        "ID": "106",
        "NAME": "Nelson at Howe",
        "ADDRESS": "NE corner of intersection",
        "TYPE": "Automated Public Toilet",
        "LOCATION": "Downtown",
        "FIELD6": "24 hrs",
        "WINTERHOURS": "24 hrs",
        "WHEELCHAIR": "No",
        "FIELD9": "Please call 311 for maintenance requests",
        "LATITUDE": "49.2796964",
        "LONGITUDE": "-123.123516",
        "MAINTAINER": "City of Vancouver"
    },
    {
        "ID": "107",
        "NAME": "Powell at Main",
        "ADDRESS": "NW corner of intersection",
        "TYPE": "Automated Public Toilet",
        "LOCATION": "Downtown",
        "FIELD6": "24 hrs",
        "WINTERHOURS": "24 hrs",
        "WHEELCHAIR": "No",
        "FIELD9": "Please call 311 for maintenance requests",
        "LATITUDE": "49.2832763",
        "LONGITUDE": "-123.099849",
        "MAINTAINER": "City of Vancouver"
    },
    {
        "ID": "108",
        "NAME": "Richards at Davie - Emery Barnes Park",
        "ADDRESS": "NW corner of intersection",
        "TYPE": "Automated Public Toilet",
        "LOCATION": "Downtown",
        "FIELD6": "24 hrs",
        "WINTERHOURS": "24 hrs",
        "WHEELCHAIR": "No",
        "FIELD9": "Please call 311 for maintenance requests",
        "LATITUDE": "49.2760544",
        "LONGITUDE": "-123.124114",
        "MAINTAINER": "City of Vancouver"
    },
    {
        "ID": "109",
        "NAME": "Robson at Granville",
        "ADDRESS": "NW corner of intersection",
        "TYPE": "Automated Public Toilet",
        "LOCATION": "Downtown",
        "FIELD6": "24 hrs",
        "WINTERHOURS": "24 hrs",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Please call 311 for maintenance requests",
        "LATITUDE": "49.2816325",
        "LONGITUDE": "-123.120082",
        "MAINTAINER": "City of Vancouver"
    },
    {
        "ID": "110",
        "NAME": "Robson at Richards",
        "ADDRESS": "NW corner of intersection",
        "TYPE": "Automated Public Toilet",
        "LOCATION": "Downtown",
        "FIELD6": "24 hrs",
        "WINTERHOURS": "24 hrs",
        "WHEELCHAIR": "No",
        "FIELD9": "Please call 311 for maintenance requests",
        "LATITUDE": "49.2803243",
        "LONGITUDE": "-123.118054",
        "MAINTAINER": "City of Vancouver"
    },
    {
        "ID": "111",
        "NAME": "Vancouver Art Gallary",
        "ADDRESS": "NE Side of VAG Building",
        "TYPE": "Automated Public Toilet",
        "LOCATION": "Downtown",
        "FIELD6": "24 hrs",
        "WINTERHOURS": "24 hrs",
        "WHEELCHAIR": "Yes",
        "FIELD9": "Please call 311 for maintenance requests",
        "LATITUDE": "49.282961",
        "LONGITUDE": "-123.119864",
        "MAINTAINER": "City of Vancouver"
    }
]


ReactDOM.render(<App washrooms={washrooms} />, document.getElementById('root'));
registerServiceWorker();
